<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="KaranevichV" name="AcceptanceTests" tests="14" failures="1" timestamp="8 Aug 2013 11:54:52 GMT" time="0.036" errors="0">
  <testcase name="testBigIntegerAssert_bigNumbersCase" time="0.005" classname="com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests"/>
  <testcase name="testBigIntegerAssert_bigNumbersEqualObjectCase" time="0.001" classname="com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests"/>
  <testcase name="testBigIntegerAssert_bigNumbersLessCase" time="0.0" classname="com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests"/>
  <testcase name="testBigIntegerAssert_bigNumbersMoreCase" time="0.001" classname="com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests"/>
  <testcase name="testBigIntegerAssert_mixNumbersLessCase" time="0.001" classname="com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests"/>
  <testcase name="testBigIntegerAssert_mixNumbersMoreCase" time="0.0" classname="com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests"/>
  <testcase name="testBigIntegerAssert_smallNumbersCase" time="0.0" classname="com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests"/>
  <testcase name="testBigIntegerAssert_smallNumbersFailCase" time="0.0" classname="com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests">
    <failure type="org.testng.TestException" message="
Expected exception java.lang.AssertionError but got org.testng.TestException: 
Expected exception java.lang.AssertionError but got java.lang.ArithmeticException: / by zero">
      <![CDATA[org.testng.TestException: 
Expected exception java.lang.AssertionError but got java.lang.ArithmeticException: / by zero
Expected exception java.lang.AssertionError but got java.lang.ArithmeticException: / by zero
	... 16 more
Caused by: java.lang.ArithmeticException: / by zero
	at com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests.testBigIntegerAssert_smallNumbersFailCase(CustomAssertUnitTests.java:89)
	... 18 more
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testBigIntegerAssert_smallNumbersFailCase -->
  <testcase name="testBigIntegerAssert_smallNumbersLessCase" time="0.0" classname="com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests"/>
  <testcase name="testBigIntegerAssert_smallNumbersMoreCase" time="0.0" classname="com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests"/>
  <testcase name="testBigIntegerAssert_smallNumbersNegativeCase" time="0.0" classname="com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests"/>
  <testcase name="isLocalTAFEnvOK" time="0.0" classname="com.organization.automation.project.spice.mix.testng.feature.abstract_tc.tests.InitializationTests_TestSet"/>
  <testcase name="isQAEnvOK" time="0.001" classname="com.organization.automation.project.spice.mix.testng.feature.abstract_tc.tests.InitializationTests_TestSet"/>
  <testcase name="isAbstractTCworks" time="0.005" classname="com.organization.automation.project.spice.mix.testng.feature.abstract_tc.tests.AcceptanceTests_Feature_AbstractTC"/>
</testsuite> <!-- AcceptanceTests -->
